default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: invoicer_saas_development

test:
  <<: *default
  database: invoicer_saas_test

production:
  <<: *default
  database: invoicer_saas_production
